### PR TITLE
Removed all vulnerabilities

### PR DESCRIPTION
**Pull request by Al38andr0**
Description in the commit

### CODE REVIEW

**Comment by wgta** [comment]
@Al38andr0 why are we removing storybook ?

**Comment by Al38andr0** [comment]
@wgta, as I mentioned in the commit description, Storybook was only used for this repo to show the components.
It was never used, or at least it was abandoned a long time ago.

Please let me know if you have more information and an good reason to keep it.

**Comment by wgta** [comment]
> @wgta, as I mentioned in the commit description, Storybook was only used for this repo to show the components. It was never used, or at least it was abandoned a long time ago.
> 
> Please let me know if you have more information and a good reason to keep it.

@Al38andr0  we have storybook hosted here
https://bridget.bridge-u.dev/?selectedKind=Components&selectedStory=Popovers&full=0&addons=1&stories=1&panelRight=0

What happens to that ?

**Comment by alexandrenicol** [comment]
@Al38andr0 I did send that link to you this morning, but as I said then, it's massively outdated and doesn't reflect what the design team is currently working on. I would suggest to remove this link, as it's not hepful for developers given that it gives outdated information.

cc @wgta

**Comment by Al38andr0** [comment]
@alexandrenicol, sorry, I was overloaded this morning and didn't notice the link.

Conclusion: we are happy to remove it, @wgta .

**Review by wgta — APPROVED** [review]

**Pull request merged**
